# Generated by Django 4.2 on 2026-05-05 01:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('shop', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField()),
                ('picture', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
